// =============================================================================
// adapters/scipy/oracles/erf-anchor-replay.ts — scipy replay shim
// =============================================================================
//
// See adapters/wolfram/oracles/erf-anchor-replay.ts for the shared
// design notes.  This shim is the scipy (bronze-tier, float64) variant;
// results were generated by the workbench's scipy adapter at
// scipy 1.17.0 / numpy 1.26.4 / Python 3.12.3 (bead
// scientist-workbench-1f8r, 2026-05-16).
//
// scipy refused 0/271 cases — it computes a float64 answer for every
// input including the T6 edge cases (NaN ⇒ NaN, ±Inf ⇒ saturation, etc).
// The output strings are float64-resolution decimals (≤ 16 significant
// digits) wrapped in the same wire shape as the higher-precision
// oracles.
//
// Note on field naming: the scipy results.json uses `id` instead of
// `input_id` (drift from the other 3 oracles' shape).  The OracleRecord
// type accepts either via the optional fields.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

interface OracleRecord {
  input_id?: string;
  id?: string;
  head:    string;
  tier?:   string;
  z?:      string | { re: string; im: string };
  args?:   string | { re: string; im: string };
  output:  string | { re: string; im: string } | null;
  failure_reason?: string;
  method:  string;
  achieved_precision: number;
  note?: string;
}

interface OracleFile {
  oracle_id: string;
  oracle_version: string;
  results: OracleRecord[];
}

const DATA_PATH = resolve(import.meta.dir, "..", "data", "erf-anchor-results.json");

let _idx: Map<string, OracleRecord> | null = null;

function recZ(r: OracleRecord): string | { re: string; im: string } | undefined {
  return r.z ?? r.args;
}

function keyOf(head: string, z: string | { re: string; im: string }): string {
  if (typeof z === "string") return `${head}|R|${z}`;
  return `${head}|C|${z.re}|${z.im}`;
}

function loadIndex(): Map<string, OracleRecord> {
  if (_idx !== null) return _idx;
  const file = JSON.parse(readFileSync(DATA_PATH, "utf8")) as OracleFile;
  _idx = new Map();
  for (const r of file.results) {
    const z = recZ(r);
    if (z === undefined) continue;
    _idx.set(keyOf(r.head, z), r);
  }
  return _idx;
}

async function main(): Promise<void> {
  const raw = JSON.parse(readFileSync(0, "utf8")) as {
    head: string;
    z: string | { re: string; im: string };
  };

  const idx = loadIndex();
  const rec = idx.get(keyOf(raw.head, raw.z));

  if (!rec) {
    process.stdout.write(JSON.stringify({
      kind: "tool_error",
      name: "OracleReplayMiss",
      message: `no committed scipy record for (head=${raw.head}, z=${JSON.stringify(raw.z)})`,
    }) + "\n");
    return;
  }

  if (rec.output === null) {
    process.stdout.write(JSON.stringify({
      kind: "tagged",
      tag: "oracle/scipy-refused",
      payload: {
        reason: rec.failure_reason ?? rec.note ?? "scipy declined to evaluate",
        method: rec.method,
      },
    }) + "\n");
    return;
  }

  process.stdout.write(JSON.stringify({
    value: rec.output,
    method: rec.method,
    achieved_precision: rec.achieved_precision,
    warnings: [],
  }) + "\n");
}

await main();
