// =============================================================================
// adapters/boost/oracles/erf-anchor-replay.ts — boost replay shim
// =============================================================================
//
// See adapters/wolfram/oracles/erf-anchor-replay.ts for the shared
// design notes.  This shim is the boost (silver-tier) variant; results
// were generated by the workbench's boost adapter at boost 1_83
// (`cpp_bin_float<50>`) via the C++ binary at
// bench/erf-anchor/oracles/boost/erf-oracle.cpp.
//
// Boost refused 122/271 cases — every complex input (`erf` has no
// std::complex specialisation in Boost.Math 1_83) plus 17 edge cases.
// All refusals carry output=null with method='boost-refused' and a
// `note` explaining the upstream cause; we surface them as tagged
// envelopes (NOT as candidate failures — the verifier's per-oracle
// checks scope themselves via applies_when).

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

interface OracleRecord {
  input_id?: string;
  id?: string;
  head:    string;
  z:       string | { re: string; im: string };
  output:  string | { re: string; im: string } | null;
  failure_reason?: string;
  method:  string;
  achieved_precision: number;
  note?: string;
}

interface OracleFile {
  oracle_id: string;
  oracle_version: string;
  results: OracleRecord[];
}

const DATA_PATH = resolve(import.meta.dir, "..", "data", "erf-anchor-results.json");

let _idx: Map<string, OracleRecord> | null = null;

function keyOf(head: string, z: string | { re: string; im: string }): string {
  if (typeof z === "string") return `${head}|R|${z}`;
  return `${head}|C|${z.re}|${z.im}`;
}

function loadIndex(): Map<string, OracleRecord> {
  if (_idx !== null) return _idx;
  const file = JSON.parse(readFileSync(DATA_PATH, "utf8")) as OracleFile;
  _idx = new Map();
  for (const r of file.results) {
    _idx.set(keyOf(r.head, r.z), r);
  }
  return _idx;
}

async function main(): Promise<void> {
  const raw = JSON.parse(readFileSync(0, "utf8")) as {
    head: string;
    z: string | { re: string; im: string };
  };

  const idx = loadIndex();
  const rec = idx.get(keyOf(raw.head, raw.z));

  if (!rec) {
    process.stdout.write(JSON.stringify({
      kind: "tool_error",
      name: "OracleReplayMiss",
      message: `no committed boost record for (head=${raw.head}, z=${JSON.stringify(raw.z)})`,
    }) + "\n");
    return;
  }

  if (rec.output === null) {
    process.stdout.write(JSON.stringify({
      kind: "tagged",
      tag: "oracle/boost-refused",
      payload: {
        reason: rec.failure_reason ?? rec.note ?? "boost declined to evaluate (no std::complex specialisation in 1_83)",
        method: rec.method,
      },
    }) + "\n");
    return;
  }

  process.stdout.write(JSON.stringify({
    value: rec.output,
    method: rec.method,
    achieved_precision: rec.achieved_precision,
    warnings: [],
  }) + "\n");
}

await main();
