// =============================================================================
// adapters/mpmath/oracles/erf-anchor-replay.ts — mpmath replay shim
// =============================================================================
//
// See adapters/wolfram/oracles/erf-anchor-replay.ts for the shared
// design notes (pre-computed-oracle pattern; reads committed
// results.json; (head, z) lookup key).  This shim is the mpmath
// (gold-tier) variant; results were generated by the workbench's
// mpmath adapter at python 3.12.3 / mpmath 1.3.0 (bead
// scientist-workbench-1f8r area; 2026-05-16).
//
// mpmath refusals: 2 cases (T6-erfc-015, T6-erfcx-023 MAX_DOUBLE
// overflow) carry output=null + a `failure_reason` string we surface
// as the tagged-refusal payload.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

interface OracleRecord {
  input_id?: string;
  id?: string;
  head:    string;
  z:       string | { re: string; im: string };
  output:  string | { re: string; im: string } | null;
  failure_reason?: string;
  method:  string;
  achieved_precision: number;
  note?: string;
}

interface OracleFile {
  oracle_id: string;
  oracle_version: string;
  results: OracleRecord[];
}

const DATA_PATH = resolve(import.meta.dir, "..", "data", "erf-anchor-results.json");

let _idx: Map<string, OracleRecord> | null = null;

function keyOf(head: string, z: string | { re: string; im: string }): string {
  if (typeof z === "string") return `${head}|R|${z}`;
  return `${head}|C|${z.re}|${z.im}`;
}

function loadIndex(): Map<string, OracleRecord> {
  if (_idx !== null) return _idx;
  const file = JSON.parse(readFileSync(DATA_PATH, "utf8")) as OracleFile;
  _idx = new Map();
  for (const r of file.results) {
    _idx.set(keyOf(r.head, r.z), r);
  }
  return _idx;
}

async function main(): Promise<void> {
  const raw = JSON.parse(readFileSync(0, "utf8")) as {
    head: string;
    z: string | { re: string; im: string };
  };

  const idx = loadIndex();
  const rec = idx.get(keyOf(raw.head, raw.z));

  if (!rec) {
    process.stdout.write(JSON.stringify({
      kind: "tool_error",
      name: "OracleReplayMiss",
      message: `no committed mpmath record for (head=${raw.head}, z=${JSON.stringify(raw.z)})`,
    }) + "\n");
    return;
  }

  if (rec.output === null) {
    process.stdout.write(JSON.stringify({
      kind: "tagged",
      tag: "oracle/mpmath-refused",
      payload: {
        reason: rec.failure_reason ?? rec.note ?? "mpmath declined to evaluate",
        method: rec.method,
      },
    }) + "\n");
    return;
  }

  process.stdout.write(JSON.stringify({
    value: rec.output,
    method: rec.method,
    achieved_precision: rec.achieved_precision,
    warnings: [],
  }) + "\n");
}

await main();
